setfpscap(7)
script_key = "hGwxOfPreWCdoHWkOreOUtvBJejDkXli";
getgenv().UserConfig = {
    ["FPS Cap"] = 7,
    ["Auto Buy Seed"] = true,
    ["Auto Plant Seed"] = true,
    ["Limit Plant Seed"] = {
        ["Carrot"] = 50, 
        ["Tulip"] = 50,
        ["Bamboo"] = 100,
        ["Corn"] = 50,
        ["Cactus"] = 50,
        ["Pineapple"] = 50,
        ["Mushroom"] = 100,
        ["Green Bean"] = 20,
        ["Banana"] = 30,
        ["Grape"] = 30,
        ["Coconut"] = 30,
        ["Mango"] = 30,
        ["Dragon Fruit"] = 25,
        ["Acorn"] = 20,
        ["Cherry"] = 20,
        ["Sunflower"] = 20,
        ["Venus Fly Trap"] = 20,
        ["Pomegranate"] = 20,
        ["Poison Apple"] = 20,
    },
    ["Limit Buy Seed"] = {
        ["Carrot"] = 50, 
        ["Tulip"] = 50,
        ["Bamboo"] = 100,
        ["Corn"] = 5,
        ["Cactus"] = 5,
        ["Pineapple"] = 5,
        ["Mushroom"] = 100,
        ["Green Bean"] = 5,
        ["Banana"] = 2,
        ["Grape"] = 2,
        ["Coconut"] = 2,
        ["Mango"] = 2,
        ["Dragon Fruit"] = 2,
        ["Acorn"] = 2,
        ["Cherry"] = 2,
        ["Sunflower"] = 2,
        ["Venus Fly Trap"] = 2,
        ["Pomegranate"] = 2,
        ["Poison Apple"] = 2,
        ["Venom Spitter"] = 10,
        ["Moon Bloom"] = 100,
        ["Dragon's Breath"] = 100,
    },
["Blacklist Shovel"] = {"Dragon's Breath", "Moon Bloom", "Ghost Pepper", "Venom Spitter", "Poison Apple", "Pomegranate", "Venus Fly Trap"},
["Shovel Plant Once"] = {},
    ["Favorite"] = {
       ["Horned Melon"] = {"Rainbow", "Gold"},
    },
    ["Buy Pets"] = {
        ["Frog"] = {Huge = 99, Rainbow = 99}, -- mua 99 Huge, 99 Rainbow (không mua pet Normal, Big)
        ["Bunny"] = {Normal = 6, Big = 99, Huge = 99, Rainbow = 99},
        ["Owl"] = {Huge = 99, Rainbow = 99},
        ["Deer"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Robin"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Bee"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Monkey"] = 999, -- mua 999 tất cả loại
        ["Bear"] = 999,
        ["Golden Dragonfly"] = 999,
        ["Unicorn"] = 999,
        ["Raccoon"] = 999,
        ["Black Dragon"] = 999,
    },
    ["Equip Pets"] = {
        {"Bunny", 6, 1},
    },
    ["Expand Plot"] = true,
    ["Plot Expansions"] = 3,
    ["Unlock Pet Slots"] = 5,
    ["Auto Collect Seed Packs"] = true,
    ["Gears"] = {
        ["Buy Gear"] = {
             "Uncommon Sprinkler",
             "Rare Sprinkler",
            "Legendary Sprinkler",
            "Super Sprinkler",
            "Super Watering Can",
        },
        ["Gears To Use"] = {
            "Uncommon Sprinkler",
             "Rare Sprinkler",
        },
    },
    ["Webhook URL"] = "https://discord.com/api/webhooks/1516792376377606144/4aO-Yrwva02ISZNd05c6iD1vdqFNnyyQLn0Jd7Sgj6Sv63LCvl1Y1vp0o9f59HM3_y63",
    ["Webhook Pet Name"] = {"Golden Dragonfly","Unicorn","Raccoon","Monkey","Bee","Ice Serpent","Robin","Deer", "Bear"},
    ["Webhook Pet Rarity"] = {"Mythic", "Super", "Secret"},
    ["Webhook Seed Name"] = {"Mega", "Rainbow", "Gold"},
    ["Webhook Note"] = "xx",
    ["Discord ID"] = "908622152834625599",
    ["Mail To Username"] = {"noopbt"},
    ["Items To Mail"] = {
        ["Pet"] = {
            ["Frog"] = 1,
            ["Owl"] = 1,
            ["Deer"] = 1,
            ["Robin"] = 1,
            ["Bee"] = 1,
            ["Bunny"] = {Big = 1, Huge = 1, Rainbow = 1},
            ["Golden Dragonfly"] = 1,
            ["Unicorn"] = 1,
            ["Raccoon"] = 1,
            ["Monkey"] = 1,
            ["Bear"] = 1,
            ["Ice Serpent"] = 1,
        },
        ["Seed"] = {
            ["Rainbow"] = 2,
            ["Mega"] = 1,
            ["Gold"] = 3,
            ["Dragon's Breath"] = 1,
            ["Venom Spitter"] = 1,
            ["Moon Bloom"] = 1,
        },
        ["Gear"] = {
            ["Super Watering Can"] = 1,
            ["Super Sprinkler"] = 1,
            ["Common Sprinkler"] = 1,
            ["Uncommon Sprinkler"] = 1,
            ["Rare Sprinkler"] = 1,
            ["Legendary Sprinkler"] = 4,
        },
    },
    ["Claim Mail"] = true,
    ["Auto Plant"] = false,
    ["Limit Auto Plant"] = 800,
    ["Blacklist Seed"] = {"Mega", "Rainbow", "Gold", "Dragon's Breath", "Venom Spitter", "Moon Bloom"}
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/66adeacbfb46c0ea4883aefee367292a.lua"))()
