setfpscap(7)
script_key = "hGwxOfPreWCdoHWkOreOUtvBJejDkXli";
getgenv().UserConfig = {
    ["FPS Cap"] = 7,
    ["Auto Buy Seed"] = true,
    ["Auto Plant Seed"] = true,
    ["Limit Plant Seed"] = {
        ["Carrot"] = 2, 
        ["Strawberry"] = 2,
        ["Blueberry"] = 2,
        ["Tulip"] = 2,
        ["Tomato"] = 2,
        ["Apple"] = 2,
        ["Bamboo"] = 100,
        ["Corn"] = 8,
        ["Cactus"] = 10,
        ["Pineapple"] = 10,
        ["Mushroom"] = 80,
        ["Green Bean"] = 120,
        ["Banana"] = 120,
        ["Grape"] = 120,
        ["Coconut"] = 120,
        ["Mango"] = 120,
        ["Dragon Fruit"] = 120,
        ["Acorn"] = 35,
        ["Cherry"] = 35,
        ["Sunflower"] = 35,
        ["Venus Fly Trap"] = 10,
        ["Pomegranate"] = 10,
        ["Venom Spitter"] = 10,
        ["Moon Bloom"] = 10,
        ["Ghost Pepper"] = 10,
        ["Poison Apple"] = 10,
    },
    ["Limit Buy Seed"] = {
        ["Carrot"] = 5, 
        ["Strawberry"] = 5,
        ["Blueberry"] = 5,
        ["Tulip"] = 5,
        ["Tomato"] = 5,
        ["Apple"] = 5,
        ["Bamboo"] = 9999,
        ["Corn"] = 5,
        ["Cactus"] = 5,
        ["Pineangle"] = 5,
        ["Mushroom"] = 9999,
        ["Green Bean"] = 5,
        ["Banana"] = 2,
        ["Grape"] = 2,
        ["Coconut"] = 2,
        ["Mango"] = 2,
        ["Dragon Fruit"] = 2,
        ["Acorn"] = 2,
        ["Cherry"] = 2,
        ["Sunflower"] = 2,
        ["Venus Fly Trap"] = 2,
        ["Pomegranate"] = 2,
        ["Poison Apple"] = 2,
        ["Venom Spitter"] = 10,
        ["Moon Bloom"] = 100,
        ["Dragon's Breath"] = 100,
    },
["Blacklist Shovel"] = {"Dragon's Breath", "Moon Bloom", "Ghost Pepper", "Venom Spitter", "Poison Apple", "Pomegranate", "Venus Fly Trap", "Mushroom", "Bamboo"},
["Shovel Plant Once"] = {},
    ["Favorite"] = {
       ["Horned Melon"] = {"Mega", "Rainbow", "Gold"},
    },
    ["Harvest Mutation Only"] = {
        ["Bamboo"] = {"Rainbow", "Gold", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora"},
        ["Mushroom"] = {"Rainbow", "Gold", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora"},  
    },
    ["Buy Pets"] = {
        ["Frog"] = {Huge = 99, Rainbow = 99}, -- mua 99 Huge, 99 Rainbow (không mua pet Normal, Big)
        ["Bunny"] = {Normal = 6, Big = 99, Huge = 99, Rainbow = 99},
        ["Owl"] = {Huge = 99, Rainbow = 99},
        ["Deer"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Robin"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Bee"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Monkey"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Bear"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Golden Dragonfly"] = 999,
        ["Unicorn"] = 999,
        ["Raccoon"] = 999,
        ["Black Dragon"] = 999,
    },
    ["Equip Pets"] = {
        {"Bunny", 6, 1},
    },
    ["Expand Plot"] = true,
    ["Plot Expansions"] = 3,
    ["Unlock Pet Slots"] = 5,
    ["Auto Collect Seed Packs"] = true,
    ["Gears"] = {
        ["Buy Gear"] = {
         "Uncommon Sprinkler",
         "Rare Sprinkler",
            "Legendary Sprinkler",
            "Super Sprinkler",
            "Super Watering Can",
        },
        ["Gears To Use"] = {
            "Uncommon Sprinkler",
             "Rare Sprinkler",
        },
    },
       -- WH Pet
    ["Webhook Pet URL"] = "https://discord.com/api/webhooks/1520466700884115558/UGQT9MHNQX8yxA3kHR073ExOKTW2DgDOrT2VpnPSKLj5PiFZX9AnKrGzvuLRo2Qe-Rxc",
    ["Webhook Pet Name"] = {"Golden Dragonfly","Unicorn","Raccoon","Monkey","Bee","Ice Serpent","Robin","Deer"},
    ["Webhook Pet Rarity"] = {"Mythic", "Super", "Secret"},
 	-- WH Seed
    ["Webhook Seed URL"] = "https://discord.com/api/webhooks/1520466518104608970/yH3BmsZZtSuvznYBGJs-57ys1zk4OJlxzWm1fF1fJM_N_wpvfhgmKt4nIMBSnf3nSgoN",
    ["Webhook Seed Name"] = {"Rainbow", "Gold", "Mega", "Dragon's Breath", "Hypno Bloom", "Moon Bloom", "Briar Rose", "Venom Spitter", "Poison Apple", "Pomegranate", "Venus Fly Trap"},
    	-- WH Gear
    ["Webhook Gear URL"] = "https://discord.com/api/webhooks/1520466786095595650/0fEwvTDJS39ZeJQ_aUDD_bCg3Ukss2YA5h-rk43y5F2V3kZgeBLSEo8prn09lvqgJ-z9",
    ["Webhook Gear Name"] = {"Super Sprinkler", "Super Watering Can"},
    ["Webhook Note"] = "ye",
    ["Discord ID"] = "908622152834625599",
    ["Mail To Username"] = {"noopbt"},
    ["Items To Mail"] = {
        ["Pet"] = {
            ["Frog"] = 1,
            ["Owl"] = 1,
            ["Deer"] = 1,
            ["Robin"] = 1,
            ["Bee"] = 1,
            ["Bunny"] = {Big = 1, Huge = 1, Rainbow = 1},
            ["Golden Dragonfly"] = 1,
            ["Unicorn"] = 1,
            ["Raccoon"] = 1,
            ["Monkey"] = 1,
            ["Bear"] = 1,
            ["Ice Serpent"] = 1,
        },
        ["Seed"] = {
            ["Rainbow"] = 2,
            ["Mega"] = 1,
            ["Gold"] = 3,
            ["Dragon's Breath"] = 1,
            ["Venom Spitter"] = 1,
            ["Moon Bloom"] = 1,
        },
        ["Gear"] = {
            ["Super Watering Can"] = 1,
            ["Super Sprinkler"] = 1,
            ["Legendary Sprinkler"] = 4,
        },
    },
    ["Claim Mail"] = true,
    ["Auto Plant"] = true,
    ["Limit Auto Plant"] = 800,
    ["Blacklist Seed"] = {"Mega", "Rainbow", "Gold", "Dragon's Breath", "Moon Bloom"}
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/66adeacbfb46c0ea4883aefee367292a.lua"))()
